name: mern-devops

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./server
    container_name: backend
    restart: always
    environment:
      - MONGO_URI=mongodb://mongodb:27017/taskapp
      - PORT=6109
    ports:
      - "6109:6109"
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./client
      args:
        VITE_API_URL: https://pavani.vjstartup.com/be/api
    container_name: frontend
    restart: always
    ports:
      - "3109:5173"
    depends_on:
      - backend

volumes:
  mongo_data: